import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Stackosaurus App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="flex h-80 items-center justify-between"
        style={{ background: "#e5e5e5" }}
      >
        <img
          className="h-80 w-80"
          src="ai_fail.png"
          alt="Image of product/service"
        />

        <div className="h-full w-3/4 p-4">
          <h3 className="mb-2 text-2xl font-semibold">Content Intro</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </p>
        </div>
      </div>
      <div style={{ background: "#e5e5e5" }}>
        <img src="/threeDesignSlides.png" alt="" className="m-auto" />
      </div>
    </>
  );
};

export default Home;
